=== eclipse-tractusx/industry-core-hub/ichub-frontend/src/schemas/idta/idta-BatteryPassCircularity-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.admin-shell.idta.batterypass.circularity:1.0.0#Circularity",
  "description" : "Dismantling information, spare part sources, recycled content, safety measures, end-of-life information and renewable content.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "DocumentIdentifierSet" : {
        "type" : "array",
        "items" : { "type" : "string", "minLength" : 1 },
        "uniqueItems" : true
      },
      "MultiLanguageTexts" : {
        "type" : "array",
        "items" : { "type" : "object" },
        "uniqueItems" : true
      },
      "PostalAddress" : {
        "type" : "object",
        "properties" : {
          "NationalCode" : { "$ref" : "#/components/schemas/MultiLanguageTexts" },
          "PostalCode" : { "$ref" : "#/components/schemas/MultiLanguageTexts" },
          "Street" : { "$ref" : "#/components/schemas/MultiLanguageTexts" }
        },
        "required" : [ "NationalCode", "PostalCode", "Street" ]
      },
      "EmailEntity" : {
        "type" : "object",
        "properties" : {
          "EmailAddress" : { "type" : "string" },
          "TypeOfEmailAddress" : { "type" : "string" }
        },
        "required" : [ "EmailAddress" ]
      },
      "Component" : {
        "type" : "object",
        "properties" : {
          "PartName" : { "type" : "string" },
          "PartNumber" : { "type" : "string" }
        },
        "required" : [ "PartName", "PartNumber" ]
      },
      "SparePartSupplier" : {
        "type" : "object",
        "properties" : {
          "NameOfSupplier" : { "$ref" : "#/components/schemas/MultiLanguageTexts" },
          "AddressOfSupplier" : { "$ref" : "#/components/schemas/PostalAddress" },
          "EmailAddressOfSupplier" : { "$ref" : "#/components/schemas/EmailEntity" },
          "SupplierWebAddress" : { "type" : "string" },
          "Components" : { "type" : "array", "items" : { "$ref" : "#/components/schemas/Component" } }
        },
        "required" : [ "NameOfSupplier", "AddressOfSupplier", "EmailAddressOfSupplier", "SupplierWebAddress", "Components" ]
      },
      "RecycledContent" : {
        "type" : "object",
        "properties" : {
          "PreConsumerShare" : { "type" : "number" },
          "RecycledMaterial" : { "type" : "string" },
          "PostConsumerShare" : { "type" : "number" }
        },
        "required" : [ "PreConsumerShare", "RecycledMaterial", "PostConsumerShare" ]
      },
      "SafetyMeasuresEntity" : {
        "type" : "object",
        "properties" : {
          "SafetyInstructions" : { "$ref" : "#/components/schemas/DocumentIdentifierSet" },
          "ExtinguishingAgents" : { "type" : "array", "items" : { "type" : "string" } }
        },
        "required" : [ "SafetyInstructions", "ExtinguishingAgents" ]
      },
      "EndOfLifeInformationEntity" : {
        "type" : "object",
        "properties" : {
          "WastePrevention" : { "$ref" : "#/components/schemas/DocumentIdentifierSet" },
          "SeparateCollection" : { "$ref" : "#/components/schemas/DocumentIdentifierSet" },
          "InformationOnCollection" : { "$ref" : "#/components/schemas/DocumentIdentifierSet" }
        },
        "required" : [ "WastePrevention", "SeparateCollection", "InformationOnCollection" ]
      }
    }
  },
  "properties" : {
    "DismantlingAndRemovalInformation" : { "$ref" : "#/components/schemas/DocumentIdentifierSet" },
    "SparePartSources" : { "type" : "array", "items" : { "$ref" : "#/components/schemas/SparePartSupplier" } },
    "RecycledContentInformation" : { "type" : "array", "items" : { "$ref" : "#/components/schemas/RecycledContent" } },
    "SafetyMeasures" : { "$ref" : "#/components/schemas/SafetyMeasuresEntity" },
    "EndOfLifeInformation" : { "$ref" : "#/components/schemas/EndOfLifeInformationEntity" },
    "RenewableContent" : { "type" : "number" }
  },
  "required" : [ "DismantlingAndRemovalInformation", "SparePartSources", "RecycledContentInformation", "SafetyMeasures", "EndOfLifeInformation", "RenewableContent" ]
}

=== eclipse-tractusx/industry-core-hub/ichub-frontend/src/schemas/examples/idta-BatteryPass-CircularityBattery-example.json
{
  "DismantlingAndRemovalInformation": [
    "d0Dds"
  ],
  "SparePartSources": [
    {
      "NameOfSupplier": [
        {
          "en": "ABC Company"
        }
      ],
      "AddressOfSupplier": {
        "NationalCode": [
          {
            "en": "DE"
          }
        ],
        "PostalCode": [
          {
            "de": "DE-10719"
          }
        ],
        "Street": [
          {
            "de": "Musterstrasse 1"
          }
        ]
      },
      "EmailAddressOfSupplier": {
        "EmailAddress": "email@muster-ag.de",
        "PublicKey": {
          "en": "0x07"
        },
        "TypeOfEmailAddress": "office",
        "TypeOfPublicKey": {
          "en": "RSA"
        }
      },
      "SupplierWebAddress": "https://example.com/information/product/1224/contact",
      "Components": [
        {
          "PartName": "Cell",
          "PartNumber": "PnYAVw"
        }
      ]
    }
  ],
  "RecycledContentInformation": [
    {
      "PreConsumerShare": 77.21,
      "RecycledMaterial": "Cobalt",
      "PostConsumerShare": 67.28
    }
  ],
  "SafetyMeasures": {
    "SafetyInstructions": [
      "2WoCFW"
    ],
    "ExtinguishingAgents": [
      "0ds2fkjV"
    ]
  },
  "EndOfLifeInformation": {
    "WastePrevention": [
      "ojb"
    ],
    "SeparateCollection": [
      "Z9"
    ],
    "InformationOnCollection": [
      "caavIHWpl"
    ]
  },
  "RenewableContent": -12143.4
}
